---
author: "Michael Koohafkan"
title: "Quickstart with vbar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quickstart} 
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The `vbar` package provides an approach to calling VBA Macros from R.
At its core, the package provides methods for programatically
constructing VBScript files that can be called from the shell, e.g.,
via `system2()`.


```r
library(vbar)
```

Scripts are generated from a skeleton script with placeholders for
macro-specific information. The package includes a default skeleton
script for basic usage, but custom skeleton scripts can be used
instead:


```r
default_skeleton(print = TRUE)
```

```
## Option Explicit
## On Error Resume Next
## 
## Dim args
## Set args = wScript.Arguments
## 
## {dim_args}
## 
## {assign_args}
## 
## Dim macroApp
## Dim macroFile
## 
## Set macroApp = createObject("{macro_application}.Application")
## macroApp.visible = False
## Set macroFile = macroApp.{collection_type}.Open("{macro_file}")
## 
## If Err.Number <> 0 Then
##   WScript.Echo "VBScript Error: " & Err.Description
##   macroApp.Quit
##   wscript.quit
## End If
## 
## macroApp.Run "{macro_name}", {macro_args}
## 
## If Err.Number <> 0 Then
##   WScript.Echo "VBScript Error: " & Err.Description
##   macroApp.Quit
##   wscript.quit
## End If
## 
## macroFile.Close
## macroApp.Quit
```

```
## [1] "C:/LocalWorkspace/g2encmck/Repositories/vbar/inst/scripts/skeleton.vbs"
```

The package provides two methods for interfacing with VBA macros.
To illustrate these methods, we'll use a macro-enabled Excel
workbook "data_importer.xlsm". This file contains a single macro
"importData" which copies data from a csv file to a sheet and cell
specified by the user and saves the result to a new Excel file. For
reference, the macro VBA code is included below:

```vb
Sub importData(inputFile As String, sheetName As String, tableRange As String, outputFile As String)
    'declarations
    Dim wsheet As Worksheet
    Set wsheet = ActiveWorkbook.Sheets(sheetName)
    'read data from file
    With wsheet.QueryTables.Add(Connection:="TEXT;" & inputFile, Destination:=wsheet.Range(tableRange))
        .TextFileParseType = xlDelimited
        .TextFileCommaDelimiter = True
        .RefreshOnFileOpen = False
        .Refresh BackgroundQuery:=False
        .Refresh
    End With
    'remove connection when finished
    Dim Conn As WorkbookConnection
    For Each Conn In ThisWorkbook.Connections
        If InStr(1, inputFile, Conn.Name, 1) > 0 Then
            Conn.Delete
        End If
    Next Conn
    ActiveWorkbook.SaveAs (outputFile)
End Sub
```

This macro file is included in the package. Note that if you
unsigned macros are disabled from running on your machine, you
may need to
[self-sign the Excel file](Digitally sign your VBA macro project https://support.microsoft.com/en-au/office/digitally-sign-your-vba-macro-project-956e9cc8-bbf6-4365-8bfa-98505ecd1c01).


```r
# get path to data_importer.xlsm
example_file = normalizePath(system.file("examples", "data_importer.xlsm",
  package = "vbar"), mustWork = TRUE)

# navigate to the file and re-sign if necessary:
print(example_file)
```

```
## [1] "C:\\LocalWorkspace\\g2encmck\\Repositories\\vbar\\inst\\examples\\data_importer.xlsm"
```

The macro accepts four arguments:

1. The path to the csv file containing data.
2. The target sheet in "data_importer.xlsm" to write data to.
3. The target cell defining the top-left corner of the data table to be
   written.
4. The path of the new Excel file to be saved.

For this example, we'll also create some dummy data to import.


```r
# create dummy data
set.seed(42)
dummy_file = normalizePath(tempfile(fileext = ".csv"), mustWork = FALSE)
write.csv(data.frame(x = seq_len(10), y = rnorm(10)), dummy_file,
  row.names = FALSE)
```

## 1. Generate a script file from a list of arguments

This method produces a VBS script that calls the specified macro. All
arguments to the macro must be passed as named R arguments with default
values in order to perform the correct type casting in the resulting
VBScript.


```r
myscript = macro_script(example_file, "importData",
  inputFile = character(), targetSheet = character(),
  targetRange = character(), outputFile = character())

myscript
```

```
## Option Explicit
## On Error Resume Next
## 
## Dim args
## Set args = wScript.Arguments
## 
## Dim inputFile
## Dim targetSheet
## Dim targetRange
## Dim outputFile
## 
## inputFile = args(0)
## targetSheet = args(1)
## targetRange = args(2)
## outputFile = args(3)
## 
## Dim macroApp
## Dim macroFile
## 
## Set macroApp = createObject("Excel.Application")
## macroApp.visible = False
## Set macroFile = macroApp.Workbooks.Open("C:\LocalWorkspace\g2encmck\Repositories\vbar\inst\examples\data_importer.xlsm")
## 
## If Err.Number <> 0 Then
##   WScript.Echo "VBScript Error: " & Err.Description
##   macroApp.Quit
##   wscript.quit
## End If
## 
## macroApp.Run "importData", CStr(inputFile), CStr(targetSheet), CStr(targetRange), CStr(outputFile)
## 
## If Err.Number <> 0 Then
##   WScript.Echo "VBScript Error: " & Err.Description
##   macroApp.Quit
##   wscript.quit
## End If
## 
## macroFile.Close
## macroApp.Quit
```

This script can then be written to a file and run via `system2()`:


```r
# write script to file
script_file = normalizePath(tempfile(fileext = ".vbs"), mustWork = FALSE)
writeLines(myscript, script_file)

#specify macro output file
output_file = normalizePath(tempfile(fileext = ".xlsm"), mustWork = FALSE)

# run macro via VBScript
system2("cscript", args = c(script_file, dummy_file, "second_sheet",
  "B2", output_file))
```

When you open the resulting Excel file, you should see the dummy data
written to sheet "second_sheet" starting at cell B2.


```r
shell.exec(output_file)
```

## 2. Generate an R function that calls the script file

This method wraps the functionality of the previous method into a
callable R function. 


```r
macro_fun = macro_function(example_file, "importData",
  dataFile = character(), targetSheet = character(),
  targetRange = character(), outputFile = character())
```

VBScripts created by `macro_function()` are stored in a temporary
directory managed by the package. The VBScript file names match the
specified macro names. 


```r
script_dir()
```

```
## [1] "C:\\Temp\\3\\RtmpgbJN6H\\vbar709817c85de7"
```

```r
list.files(script_dir())
```

```
## [1] "importData.vbs"
```

Using `macro_function()` allows macros to be called like any other R function.


```r
output_file2 = normalizePath(tempfile(fileext = ".xlsm"), mustWork = FALSE)

macro_fun(dummy_file, "first_sheet", "A1", output_file2)
```


When you open the resulting Excel file, you should see the dummy data
written to sheet "first_sheet" starting at cell A1.


```r
shell.exec(output_file2)
```

# Common Problems

VBScript is is fairly sensitive to syntax and type errors, and has only
rudimentary support for error handling. Below is a list of common
problems in VBScripts:

1. **Macros are not enabled in the file**. Unsurprisingly, attempting
   to run macros from a file that has macros disabled will result in an
   error. Some methods of copying Macro-Enabled files will remove
   digital signatures from the files, disabling macros.
2. **Mixed formatting in file paths**. While VBScript can handle file paths
   that use either `/` or `\`, it cannot handle file paths that use
   both. To avoid this problem, wrap any file paths provided as macro
   arguments in `normalizePath()` to ensure consistent formatting. Note
   that `macro_script()` and `macro_function()` will normalize the path
   to the macro file internally.
3. **VBA errors**. VBScript will not return errors thrown by the macro
   code. Depending on how the macro is written, the error may result in
   an interactive dialog box, which suspend the program rather than
   closing it. Setting `Application.DisplayAlerts = False` in your VBA
   macros will prevent the application from prompting the user to save
   the file when an error is encountered, but errors must be handled in
   the VBA macro in order to completely prevent interactive dialogs and
   avoid VBScripts from hanging indefinitely. Unfortunately, I do not
   know of a way to return values from a VBA macro back to VBScript so
   the best-case scenario will be that the VBScript returns an
   "unknown error" message. 
